### ISSUE TITLE
Array output not working

### ISSUE THREAD

**Issue by wakproductions** [taylorzr/verbalize#26]
I'm following your example:
```ruby
outcome, value = Add.call(a: 35, b: 7)
```

First of all, for this piece of code to work you need to call `#to_ary` so I think the example may be incorrect. Additionally, might be best to stick with Ruby convention and alias `#to_ary` with `#to_a`.

Second problem, I'm unable to access `#value` when the condition is failure:

```ruby
From: /Users/wkotzan/Development/banks/lib/url_tools/resolve.rb @ line 110 UrlTools::Resolve#recursively_resolve:

    101: def recursively_resolve(redirect_url)
    102:   result = self.class.call(
    103:     url: redirect_url,
    104:     agent: agent,
    105:     current_level: current_level + 1,
    106:     use_redis_cache: use_redis_cache
    107:   )
    108: 
    109:   binding.pry
 => 110:   result.failure? ? fail!(result.value) : result.value
    111: end

[1] pry(#<UrlTools::Resolve>)> result
=> #<Verbalize::Failure:0x007fbc19d9eae0 @outcome=:error, @value="ERROR: circular redirect">
[2] pry(#<UrlTools::Resolve>)> result.value
Verbalize::Error: You called #value on a Failure result.  You should never use `Verbalize::Action#call` without also explicitly handling potential errors.  Please use `Verbalize::Action#call!` to return a value directly on successful execution of an action, or handle the error case explicitly if using `#call`.
from /Users/wkotzan/.rvm/gems/ruby-2.3.1@banks/gems/verbalize-2.1.1/lib/verbalize/failure.rb:17:in `value'
```

I stuffed an error message in value, but I can't get to it! Is there a supposedly different way of handling error messages?

**Comment by wakproductions** [comment]
Nevermind on my first feedback of `#to_ary` vs `#to_a`. Didn't know about this convention until now: http://stackoverflow.com/questions/9467395/whats-the-difference-between-to-a-and-to-ary

But still in my tests I'm doing this:
```ruby
  subject(:resolve) { UrlTools::Resolve.call(url: initial_request_url).to_ary }
  it { is_expected.to eql([:ok, redirected_to_url]) }
```

Think that is an OK practice?

I got around the other Verbalize error by rewriting my method as this:
```
    def recursively_resolve(redirect_url)
      outcome, result = self.class.call(
        url: redirect_url,
        agent: agent,
        current_level: current_level + 1,
        use_redis_cache: use_redis_cache
      )

      outcome==:error ? fail!(result) : result
    end
```

But still... that's a bizarre inconsistency that I can access the value as an array but not by the instance method.

**Comment by tmertens** [comment]
@wakproductions Just to clarify, you are saying that the original issue is not actually an issue correct?  There are tests in place that demonstrate array assignment works as expected.

Regarding the `#value` method, use of this for accessing the failure message on `fail!` was deprecated in Verbalize v2.x in favor of the `#failure` method for accessing failures.

If you are explicitly handling a failure via `call`, you should access the failure message using the `failure` method on the Failure result rather than `value` method which is available on Success results.

Lastly, in your example you don't actually do anything with failures except throwing them up the stack.  In this case, you should just use `call!` instead of `call`, which will automatically throw up the stack until it hits a Verbalize::Action `call` to catch the error and will be faster since you aren't repeatedly throwing over and over again.

**Comment by wakproductions** [comment]
Correct, the `#to_ary` is not so much an issue. It's just that the way I was testing against it didn't perform the implicit conversion. IMO I would add a `#to_a` alias for cases where you want explicit conversion.

Thanks for clarifying use of `failure` vs `value`. That wasn't apparent to me in the docs. 

I don't think `#call!` vs `#call` would work for me in this case without some further refactoring. But thanks for the suggestion - will keep in mind.

**Comment by taylorzr** [comment]
Yea, I've just called *to_ary* in tests where I want to get an array of [result, return_value], but I guess *to_a* would be a more standard way to do that. 

Feel free to open an issue or pull-request if you think implementing *to_a* is important. Closing this issue for now.
